package online.lisikha.probe
import android.net.Network
import com.jcraft.jsch.JSch
import com.jcraft.jsch.SocketFactory
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.*
import java.net.*
class SshCommander{suspend fun exec(n:Network?,host:String,port:Int,user:String,password:String,cmd:String):String=withContext(Dispatchers.IO){val s=JSch().getSession(user,host,port);s.setConfig("StrictHostKeyChecking","no");s.setPassword(password);if(n!=null)s.setSocketFactory(object:SocketFactory{override fun createSocket(h:String,p:Int):Socket=n.socketFactory.createSocket().apply{connect(InetSocketAddress(h,p),8000)};override fun getInputStream(x:Socket):InputStream=x.getInputStream();override fun getOutputStream(x:Socket):OutputStream=x.getOutputStream()});s.connect(10000);try{val ch=s.openChannel("exec") as com.jcraft.jsch.ChannelExec;ch.setCommand(cmd);val i=ch.inputStream;val e=ch.errStream;ch.connect(8000);val out=StringBuilder();val b=ByteArray(4096);while(!ch.isClosed){while(i.available()>0){val k=i.read(b);if(k<0)break;out.append(String(b,0,k))};while(e.available()>0){val k=e.read(b);if(k<0)break;out.append(String(b,0,k))};Thread.sleep(80)};ch.disconnect();out.toString().ifBlank{"Exit ${ch.exitStatus}"}}finally{s.disconnect()}}}
object SafeAiPlanner{data class Plan(val label:String,val command:String);private val ps=listOf(listOf("статус xray","xray status") to Plan("Xray status","systemctl status xray --no-pager -l | tail -n 60"),listOf("перезапусти xray","рестарт xray","restart xray") to Plan("Restart Xray","systemctl restart xray && systemctl is-active xray"),listOf("логи xray","xray logs") to Plan("Xray logs","journalctl -u xray -n 80 --no-pager"),listOf("аптайм","uptime") to Plan("Uptime","uptime"),listOf("память","memory") to Plan("Memory","free -h"),listOf("диск","disk") to Plan("Disk","df -h /"),listOf("порты","ports") to Plan("Ports","ss -lntp | head -n 100"),listOf("сеть","network") to Plan("Network","ip -br a; ip route; curl -4 -s https://api.ipify.org; echo"));fun plan(t:String):Plan?{val q=t.lowercase();return ps.firstOrNull{(k,_)->k.any{q.contains(it)}}?.second}}
